user:
    resource: "@UserBundle/Resources/config/routing.yml"

app.index:
    resource: "@AppBundle/Controller/IndexController.php"
    type: annotation
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /super